
package com.procemientos.almacenados;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Christian Ramirez
 */
public class Procedimientos extends javax.swing.JFrame {

    Conexion instanciaMysql = Conexion.getInstance();
    
    /**
     * Creates new form Procedimientos
     */
    public Procedimientos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ProyectoFinal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtFecha1 = new javax.swing.JTextField();
        txtFecha2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda Por Fecha"));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Buscar por rango de fechas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Buscar y Guardar TXT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Digite Fecha1 (yyyy-mm-dd)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Digite Fecha2 (yyyy-mm-dd)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFecha2)
                    .addComponent(txtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario Libreria Emanuel"));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabla);

        jButton4.setText("Guardar todos los registros en TXT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Mostrar Todos los registros del inventario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     

        
        try{
            
            
            Connection conexion = instanciaMysql.conectar();
            CallableStatement procedimientoAlmacenado = conexion.prepareCall("{call Mostrar}");
            ResultSet consulta = procedimientoAlmacenado.executeQuery();
            ResultSetMetaData consulta1 = consulta.getMetaData();
            
            int numerocolumnas=consulta1.getColumnCount();
            
            DefaultTableModel modelo = new DefaultTableModel();
            this.Tabla.setModel(modelo);
            
            for(int x=1; x<=numerocolumnas;x++){
            modelo.addColumn(consulta1.getColumnLabel(x));
            }
            
            while (consulta.next()){
            Object[] fila = new Object [numerocolumnas];
            
            
                for(int y=0; y<numerocolumnas;y++){
                fila[y]=consulta.getObject(y+1);
                }
                modelo.addRow(fila);
            }   
        }
        
        catch(SQLException se){
        }
        
        // Creamos las columnas.
 
            
       
            
            
            
            /* try{
            
            Connection conexion = instanciaMysql.conectar();
            CallableStatement procedimientoAlmacenado = conexion.prepareCall("{call Mostrar}");
            ResultSet consulta = procedimientoAlmacenado.executeQuery();
            
            
            
            
            
            area.setText("");
            while(consulta.next()){
            area.append((consulta.getInt(1) + "                "));
            area.append((consulta.getString(2) + "       "));
            area.append((consulta.getString(3) + "       "));
            area.append((consulta.getInt(4) + "       "));
            area.append((consulta.getInt(5) + "             "));
            area.append((consulta.getInt(6) + "              "));
            area.append((consulta.getInt(7) + "              "));
            area.append((consulta.getInt(8) + "               "));
            area.append((consulta.getString(9) + "       "));
            
            
            area.append("\n");
            }
            
            procedimientoAlmacenado.close();
            instanciaMysql.desconectar(conexion);
            }catch(SQLException error){
            System.out.println(error);
            }  */
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
         try{
            
            
            Connection conexion = instanciaMysql.conectar();
            CallableStatement procedimientoAlmacenado = conexion.prepareCall("{call buscar(?,?)}");
            
            procedimientoAlmacenado.setString(1,txtFecha1.getText());
            procedimientoAlmacenado.setString(2,txtFecha2.getText());
            
            
            ResultSet consulta = procedimientoAlmacenado.executeQuery();
            ResultSetMetaData consulta1 = consulta.getMetaData();
            
            int numerocolumnas=consulta1.getColumnCount();
            
            DefaultTableModel modelo = new DefaultTableModel();
            this.Tabla.setModel(modelo);
            
            for(int x=1; x<=numerocolumnas;x++){
            modelo.addColumn(consulta1.getColumnLabel(x));
            }
            
            while (consulta.next()){
            Object[] fila = new Object [numerocolumnas];
            
            
                for(int y=0; y<numerocolumnas;y++){
                fila[y]=consulta.getObject(y+1);
                }
                modelo.addRow(fila);
            }   
        }
        
        catch(SQLException se){
        }

       /*  try{

            
            Connection conexion = instanciaMysql.conectar();
            CallableStatement procedimientoAlmacenado = conexion.prepareCall("{call buscar(?,?)}");

            procedimientoAlmacenado.setString(1,txtFecha1.getText());
            procedimientoAlmacenado.setString(2,txtFecha2.getText());

              area.setText("");
            
           ResultSet consulta = procedimientoAlmacenado.executeQuery();
            
            while(consulta.next()){
               area.append((consulta.getInt(1) + "                "));
                area.append((consulta.getString(2) + "       "));
                area.append((consulta.getString(3) + "       "));
                area.append((consulta.getInt(4) + "       "));
                area.append((consulta.getInt(5) + "             "));
                area.append((consulta.getInt(6) + "              "));
                area.append((consulta.getInt(7) + "               "));
                area.append((consulta.getInt(8) + "               "));
                area.append((consulta.getString(9) + "       "));
               
                

                area.append("\n");
            }

            JOptionPane.showMessageDialog(null,"Busqueda completada");

            procedimientoAlmacenado.close();
            instanciaMysql.desconectar(conexion);
        }catch(SQLException error){
            System.out.println(error);
        } */
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

            try{
            
            Connection conexion = instanciaMysql.conectar();
            CallableStatement procedimientoAlmacenado = conexion.prepareCall("{call GuardarRegistrosTXT}");
            ResultSet consulta = procedimientoAlmacenado.executeQuery();
                  
            JOptionPane.showMessageDialog(null,"Registros Guardados Exitosamente");
            procedimientoAlmacenado.close();
            instanciaMysql.desconectar(conexion);
        }catch(SQLException error){
            JOptionPane.showMessageDialog(null,"Error, registros ya guardados");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

         try{
            
            Connection conexion = instanciaMysql.conectar();
            CallableStatement procedimientoAlmacenado = conexion.prepareCall("{call buscarExportar(?,?)}");
            procedimientoAlmacenado.setString(1,txtFecha1.getText());
            procedimientoAlmacenado.setString(2,txtFecha2.getText());
            ResultSet consulta = procedimientoAlmacenado.executeQuery();
                  
            JOptionPane.showMessageDialog(null,"Busqueda Guardada Exitosamente");
            procedimientoAlmacenado.close();
            instanciaMysql.desconectar(conexion);
        }catch(SQLException error){
            JOptionPane.showMessageDialog(null,"Error, busqueda ya guardada");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Procedimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Procedimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Procedimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Procedimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Procedimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtFecha1;
    private javax.swing.JTextField txtFecha2;
    // End of variables declaration//GEN-END:variables
}
